### ISSUE TITLE
Add commands

### ISSUE THREAD

**Issue by rocosttaa** [jerzybalcer/Haxball_Discord_Bot#2]
Do you have an example of how I add commands in bot discord to work right in the room?

**Comment by jerzybalcer** [comment]
This code doesn't support executing discord commands from the room. You can only use room-affecting discord commands from discord.

**Comment by rocosttaa** [comment]
Can't pull anything from the room?

**Comment by jerzybalcer** [comment]
You can do it, for example by saving the data you want to pull to page local storage.
`localStorage.setItem("savedData", JSON.stringify(data))`;

Then in the node app use puppeteer's page object to get saved data. 
`let pulledData = JSON.parse( await page.evaluate(() => window.localStorage.getItem("savedData")))`;

When it's done you can pass it to discord etc.
